# The main entry point of your workflow.
# After configuring, running snakemake -n in a clone of this repository should successfully execute a dry-run of the workflow.


report: "report/workflow.rst"

localrules: all,
    genome, transcriptome, genesets,
    decoys, gentrome

# Allow users to fix the underlying OS via singularity.
singularity: "docker://continuumio/miniconda3"


rule all:
    input:
        # The first rule should define the default target files
        # Subsequent target rules can be specified below. They should start with all_*.
        'results/salmon_index',
        'results/txp2gene.tsv'


include: "rules/common.smk"
include: "rules/salmon.smk"
include: "rules/other.smk"
